version: "2.1"

services:
  http:
    image: wyveo/nginx-php-fpm:php74
    volumes:
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/sites/pbr20
    ports:
      - "56709:56709"
